
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Custom services like the smartcar will be configured here
smartcar:
  platform: auth_client

logger:
  default: info
  logs:
    homeassistant.components.cloud: debug

